# MySQL. Versions 5.0 and up are supported.
default: &default
  adapter: mysql2
  collation: utf8mb4_unicode_ci
  encoding: utf8mb4
  password:
  pool: 5
  socket: /tmp/mysql.sock
  username: root

development:
  <<: *default
  database: tundra_development

test:
  <<: *default
  database: tundra_test

production:
  <<: *default
  adapter: mysql2
  collation: utf8mb4_unicode_ci
  encoding: utf8mb4
  pool: <%%= [Integer(ENV.fetch('MAX_THREADS', 5)), Integer(ENV.fetch('DB_POOL', 5))].max %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>
